SELECT 'YOUNGEST' AS TYPE, NAME, BIRTHDAY
FROM worker
WHERE BIRTHDAY IN (SELECT MIN(BIRTHDAY) FROM worker)

UNION ALL

SELECT 'ELDEST' AS TYPE, NAME, BIRTHDAY
FROM worker
WHERE BIRTHDAY IN (SELECT MAX(BIRTHDAY) FROM worker);